[tool.poetry]
name = "infinityincursion"
version = "0.1.0"
description = ""
authors = ["octojon <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
adventurelib = "^1.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
